### ISSUE TITLE
Support `OnceCell` and remove `lazy_static` 

### ISSUE THREAD

**Issue by gabhijit** [ystero-dev/scalpel#42]
Functionality provided by `lazy_static` is now available as a part of `core` and `std` as `OnceCell`. This can be used in places where we are using `lazy_static`.

**Comment by gabhijit** [comment]
@csking101 : Do you want to take up this?

**Comment by csking101** [comment]
Yup, I'll look into it.

**Comment by csking101** [comment]
Hi sir, after looking into `OnceCell`, I came across a few things that I wanted to discuss.

- Firstly, `OnceCell` is not [thread-safe](https://doc.rust-lang.org/std/cell/struct.OnceCell.html), instead, the proposed alternative is `OnceLock` that is a ["thread-safe OnceCell"](https://doc.rust-lang.org/std/sync/struct.OnceLock.html). So, should I look into using `OnceLock` instead of `OnceCell` (since in `std` the implementation is as such)?
- Next, there is a `LazyCell`, that initializes values on first access, however it is a part of the [nightly build](https://doc.rust-lang.org/stable/core/cell/struct.LazyCell.html), should I explore that option as well?

**Comment by gabhijit** [comment]
Yes, `OnceCell` is not thread safe, instead you can look into `OnceLock`. The semantics are a bit different. Let's try to review the approach first by making one or two small changes and then let's see what makes sense.

Yes `LazyCell` will be available only on nightly and that will be kind of limiting, in that case we can continue to work with `lazy_cell` as it is. 

So let's try and work with `OnceLock` first and then determine whether to take that approach further.

Makes Sense?

**Comment by gabhijit** [comment]
Fixed by #52
